export const Films = [
    { id: 1, title: 'Annabelle', year: '2014-2019', nation: 'US', img: 'assets/images/Annabelle.jpg', info: 'Annabelle is an allegedly haunted Raggedy Ann doll, housed in the (now closed) occult museum of the paranormal investigators Ed and Lorraine Warren. Annabelle was moved there after supposed hauntings in 1970. A character based on the doll is one of the antagonists that appear in the Conjuring Universe.' },
    { id: 2, title: 'A Quiet Place', year: '2018', nation: 'US', img: 'assets/images/AQuietPlace.jpg', info: 'The plot revolves around a father (Krasinski) and a mother (Emily Blunt) who struggle to survive and rear their children (Millicent Simmonds and Noah Jupe) in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing. Beck and Woods began developing the story while in college.' },
    { id: 3, title: 'Black Phone', year: '2022', nation: 'US', img: 'assets/images/BlackPhone.jpg', info: 'The Black Phone is a 2021 American coming-of-age supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill, who both produced with Jason Blum. It is an adaptation of the 2004 short story of the same name by Joe Hill.' },
    { id: 4, title: 'Grudge', year: '2021', nation: 'US', img: 'assets/images/Grudge.jpg', info: `Meaning of grudge in English. a strong feeling of anger and dislike for a person who you feel has treated you badly, especially one that lasts for a long time: I don't bear any grudge against you. Amanda still has/holds a grudge against me for refusing to lend her that money.` },
    { id: 5, title: 'Halloween Kills', year: '2021', nation: 'US', img: 'assets/images/HalloweenKills.jpg', info: `Halloween Kills premiered at the 78th Venice International Film Festival on September 8, 2021. The film was originally set to be theatrically released on October 16, 2020, but in July 2020, due to the COVID-19 pandemic, it was delayed to October 15, 2021.` },
    { id: 6, title: 'IT', year: '2017', nation: 'US', img: 'assets/images/IT.jpg', info: `Set in Derry, Maine, the film tells the story of The Losers' Club (Lieberher, Ray Taylor, Lillis, Wolfhard, Oleff, Jacobs, and Dylan Grazer), a group of seven outcast children who are terrorized by the eponymous being which emerges from the sewer (Skarsgård), only to face their own personal demons in the process.` },
    { id: 7, title: 'Kuntilanak', year: '2022', nation: 'Indonesia', img: 'assets/images/Kuntilanak.jpg', info: `a 2006 Indonesian horror film directed by Rizal Mantovani, (although this is not a direct translation as Kuntilanak or Pontianak) about a ghost type in Indonesian (and wider Malay) folklore. In this movie, a student whose step-father molested her moves to a boarding house in a haunted area, this is followed by a series of killings.` },
    { id: 8, title: 'Train to Busan', year: '2016', nation: 'Korean', img: 'assets/images/TrainToBusan.jpg', info: `While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan. While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.` },
    { id: 9, title: 'US', year: '2019', nation: 'US', img: 'assets/images/US.jpg', info: `Us is a 2019 American psychological horror film written and directed by Jordan Peele, starring Lupita Nyong'o, Winston Duke, Elisabeth Moss, and Tim Heidecker. The film follows Adelaide Wilson (Nyong'o) and her family, who are attacked by a group of menacing doppelgängers.` },

];
export const data = [
    { id: 1, title: 'Annabelle', cost: '1B', year: '2014-2019', nation: 'US', img: 'assets/images/Annabelle.jpg', info: 'Annabelle is an allegedly haunted Raggedy Ann doll, housed in the (now closed) occult museum of the paranormal investigators Ed and Lorraine Warren. Annabelle was moved there after supposed hauntings in 1970. A character based on the doll is one of the antagonists that appear in the Conjuring Universe.' },
    { id: 2, title: 'A Quiet Place', cost: '1.5B', year: '2018', nation: 'US', img: 'assets/images/AQuietPlace.jpg', info: 'The plot revolves around a father (Krasinski) and a mother (Emily Blunt) who struggle to survive and rear their children (Millicent Simmonds and Noah Jupe) in a post-apocalyptic world inhabited by blind monsters with an acute sense of hearing. Beck and Woods began developing the story while in college.' },
    { id: 3, title: 'Black Phone', cost: '2B', year: '2022', nation: 'US', img: 'assets/images/BlackPhone.jpg', info: 'The Black Phone is a 2021 American coming-of-age supernatural horror film directed by Scott Derrickson and written by Derrickson and C. Robert Cargill, who both produced with Jason Blum. It is an adaptation of the 2004 short story of the same name by Joe Hill.' },
    { id: 4, title: 'Grudge', cost: '2.5B', year: '2021', nation: 'US', img: 'assets/images/Grudge.jpg', info: `Meaning of grudge in English. a strong feeling of anger and dislike for a person who you feel has treated you badly, especially one that lasts for a long time: I don't bear any grudge against you. Amanda still has/holds a grudge against me for refusing to lend her that money.` },
    { id: 5, title: 'Halloween Kills', cost: '3B', year: '2021', nation: 'US', img: 'assets/images/HalloweenKills.jpg', info: `Halloween Kills premiered at the 78th Venice International Film Festival on September 8, 2021. The film was originally set to be theatrically released on October 16, 2020, but in July 2020, due to the COVID-19 pandemic, it was delayed to October 15, 2021.` },
    { id: 6, title: 'IT', year: '2017', cost: '3.5B', nation: 'US', img: 'assets/images/IT.jpg', info: `Set in Derry, Maine, the film tells the story of The Losers' Club (Lieberher, Ray Taylor, Lillis, Wolfhard, Oleff, Jacobs, and Dylan Grazer), a group of seven outcast children who are terrorized by the eponymous being which emerges from the sewer (Skarsgård), only to face their own personal demons in the process.` },
    { id: 7, title: 'Kuntilanak', cost: '4B', year: '2022', nation: 'Indonesia', img: 'assets/images/Kuntilanak.jpg', info: `a 2006 Indonesian horror film directed by Rizal Mantovani, (although this is not a direct translation as Kuntilanak or Pontianak) about a ghost type in Indonesian (and wider Malay) folklore. In this movie, a student whose step-father molested her moves to a boarding house in a haunted area, this is followed by a series of killings.` },
    { id: 8, title: 'Train to Busan', cost: '4.5B', year: '2016', nation: 'Korean', img: 'assets/images/TrainToBusan.jpg', info: `While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan. While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.` },
    { id: 9, title: 'US', cost: '6B', year: '2019', nation: 'US', img: 'assets/images/US.jpg', info: `Us is a 2019 American psychological horror film written and directed by Jordan Peele, starring Lupita Nyong'o, Winston Duke, Elisabeth Moss, and Tim Heidecker. The film follows Adelaide Wilson (Nyong'o) and her family, who are attacked by a group of menacing doppelgängers.` },

];





